import { NextResponse } from "next/server";
import { withAuth } from "next-auth/middleware";

const skipAuthPageRegExp = /^\/(login|register|resources(\/(?!add).*)?|terms-and-conditions)?$/;

export const config = {
    matcher: [
        /*
         * Match all paths except for:
         * 1. /api/, /trpc/ routes
         * 2. /_next/ (Next.js internals)
         * 3. /_proxy/, /_auth/ (special pages for OG tags proxying and password protection)
         * 4. /images/, /js/, /assets/ (inside /public)
         * 5. /_vercel (Vercel internals)
         * 6. /favicon.ico, /.*sitemap-index.xml, /.*sitemap.xml, /robots.txt (static files)
         * sitemap and robot.txt are generated by `next-sitemap`
         */
        "/((?!api/|trpc/|_next/|_vercel|images|js/|assets/|favicon.ico|.*sitemap-index.xml|.*sitemap.xml|robots.txt).*)",
    ],
};

export default withAuth(
    // `withAuth` augments your `Request` with the user's token.
    function middleware(req) {
        // console.log(req.nextauth.token, 111);
    },
    {
        callbacks: {
            authorized({ req, token }) {
                return skipAuthPageRegExp.test(req.nextUrl.pathname) || !!token;
            }
        },
    }
);